name: auto-release

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Terraform
    uses: ./.github/workflows/reusable_auto_release.yml
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}