name: auto-release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Print Title of PR
        run:
          |
          echo PR No. is - ${{ jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH" }}
          echo "`jq --raw-output .pull_request.number "GITHUB_EVENT_PATH`" > config.json
