name: auto-release

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on:
      - self-hosted
    steps:
      - name : Print Title of PR
        run: echo PR Title is - ${{ jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH" }}