on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print PR Number
        run:
          |
          echo Number one: ${{ github.event.number }}
          echo Number two: ${{ github.event.pull_request.number }}