name: auto-release

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on:
      - self-hosted
    steps:
      - name : Print Title of PR
        run: echo PR Title is - ${{ github.event.pull_request.title }}