name: auto-release

on:
  push:
    branches:
      - main

jobs:
  print_pr_number:
    name: PR Number Printer
    runs-on:
      - self-hosted
    steps:
      - name : Print Title of PR
        run:
          | 
          echo PR No. is - ${{ jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH" }}
          echo "`jq --raw-output .pull_request.number "GITHUB_EVENT_PATH`" > config.json
