name: FileCheck

on:
  workflow_call:

jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if files changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - ${{ inputs.image-language }}/${{ inputs.version }}/**
