name: Auto Release

on:
  workflow_call:
    secrets:
      gh_pat:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get PR from latest merged commit to master
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        name: Get Merged PR
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.gh_pat }}
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        name: Releaser
        with:
          publish: ${{ !contains(steps.get-merged-pull-request.outputs.labels, 'no-release') }}
          prerelease: false
          config-name: auto-release-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.gh_pat }}
