name: Test Checkov
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read CVEs to skip
        id: cves
        run: |
          echo "::set-output name=to_skip::$(cat skip_checks.txt)"
      - name: Display CVEs
        run: echo ${{ steps.cves.outputs.to_skip }}
#      - name: Run Checkov action
#        id: checkov
#        uses: bridgecrewio/checkov-action@master
#        with:
#          directory: example/
#          check: CKV_AWS_1 # optional: run only a specific check_id. can be comma separated list
#          skip_check: CKV_AWS_2 # optional: skip a specific check_id. can be comma separated list
#          config_file: path/this_file