name: Initial

on:
  workflow_call:
    inputs:
      test_input:
        required: true
        type: string
        description: ignore
    secrets:
      test_token:
        required: true

jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          echo Secret: ${{ secrets.test_token }}
          echo Var: ${{ inputs.test_input }}

