name: Secondary

on: [ push ]
env:
  MY_SECRET: ${{ secrets.SUPER_SECRET_VAR }}
jobs:
  golang16:
    uses: ./.github/workflows/workflow1.yml
    secrets:
      test_token: ${{ secrets.SUPER_SECRET_VAR }}