name: Initial

on:
  workflow_call:
    secrets:
      test_token:
        required: true

jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: echo ${{ secrets.test_token }}

